# Generated by Django 4.2.10 on 2024-02-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Элкмент',
                'verbose_name_plural': 'Элементы',
            },
        ),
    ]
